downRoll: downRoll.o render.o raster.o model.o music.o effects.o psg.o events.o input.o isr.o menu.o splash.o clear.o video.o ikbd.o vbl.o 
	cc68x -g downRoll.o render.o raster.o model.o music.o effects.o psg.o events.o input.o isr.o menu.o splash.o clear.o video.o ikbd.o vbl.o -o downRoll
	
downRoll.o: downRoll.c downroll.h render.h raster.h model.h events.h
	cc68x -g -c downRoll.c
	
render.o: render.c render.h model.h
	cc68x -g -c render.c
	
raster.o: raster.c raster.h
	cc68x -g -c raster.c
	
model.o: model.c model.h
	cc68x -g -c model.c
	
psg.o: psg.c psg.h
	cc68x -g -c psg.c
	
music.o: music.c music.h
	cc68x -g -c music.c
	
effects.o: effects.c effects.h
	cc68x -g -c effects.c
	
events.o: events.c events.h
	cc68x -g -c events.c
	
input.o: input.c input.h
	cc68x -g -c input.c
	
isr.o: isr.c isr.h
	cc68x -g -c isr.c
	
menu.o: menu.c menu.h
	cc68x -g -c menu.c
	
splash.o: splash.c splash.h
	cc68x -g -c splash.c
	
clear.o: clear.s clear.h
	gen -D -L2 clear.s
	
video.o: video.s video.h
	gen -D -L2 video.s
	
ikbd.o: ikbd.s ikbd.h
	gen -D -L2 ikbd.s
	
vbl.o: vbl.s vbl.h
	gen -D -L2 vbl.s
	